// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consistency.proto

package org.common.raft;

public interface HotKeyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HotKeyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>int64 createTime = 1;</code>
   */
  long getCreateTime();

  /**
   * <pre>
   *热点key
   * </pre>
   *
   * <code>string key = 2;</code>
   */
  java.lang.String getKey();
  /**
   * <pre>
   *热点key
   * </pre>
   *
   * <code>string key = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <pre>
   *app名称
   * </pre>
   *
   * <code>string appName = 3;</code>
   */
  java.lang.String getAppName();
  /**
   * <pre>
   *app名称
   * </pre>
   *
   * <code>string appName = 3;</code>
   */
  com.google.protobuf.ByteString
      getAppNameBytes();

  /**
   * <pre>
   *请求的次数
   * </pre>
   *
   * <code>int32 count = 4;</code>
   */
  int getCount();

  /**
   * <pre>
   *是删除还是添加
   * </pre>
   *
   * <code>.WriteType type = 5;</code>
   */
  int getTypeValue();
  /**
   * <pre>
   *是删除还是添加
   * </pre>
   *
   * <code>.WriteType type = 5;</code>
   */
  org.common.raft.WriteType getType();
}
