// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consistency.proto

package org.common.raft;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string errMsg = 2;</code>
   */
  java.lang.String getErrMsg();
  /**
   * <code>string errMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrMsgBytes();

  /**
   * <code>bool success = 3;</code>
   */
  boolean getSuccess();

  /**
   * <code>bytes data = 4;</code>
   */
  com.google.protobuf.ByteString getData();
}
