// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.raft.rpc;

public interface HeartBeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.HeartBeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string errorMessage = 2;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>bytes data = 3;</code>
   */
  com.google.protobuf.ByteString getData();
}
