// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consistency.proto

package org.raft.rpc;

public interface KeyDistributionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:KeyDistributionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string workerId = 1;</code>
   */
  java.lang.String getWorkerId();
  /**
   * <code>string workerId = 1;</code>
   */
  com.google.protobuf.ByteString
      getWorkerIdBytes();

  /**
   * <code>.HotKeyRequest request = 2;</code>
   */
  boolean hasRequest();
  /**
   * <code>.HotKeyRequest request = 2;</code>
   */
  org.raft.rpc.HotKeyRequest getRequest();
  /**
   * <code>.HotKeyRequest request = 2;</code>
   */
  org.raft.rpc.HotKeyRequestOrBuilder getRequestOrBuilder();
}
