// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.raft.rpc;

public final class Server {
  private Server() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_HeartBeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_HeartBeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_HeartBeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_HeartBeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\022\005jraft\032\031google/protobuf/a" +
      "ny.proto\032\037google/protobuf/timestamp.prot" +
      "o\032\036google/protobuf/wrappers.proto\"T\n\020Hea" +
      "rtBeatRequest\022/\n\ttimestamp\030\001 \001(\0132\034.googl" +
      "e.protobuf.UInt64Value\022\017\n\007payload\030\002 \001(\014\"" +
      "H\n\021HeartBeatResponse\022\017\n\007success\030\001 \001(\010\022\024\n" +
      "\014errorMessage\030\002 \001(\t\022\014\n\004data\030\003 \001(\014B\020\n\014org" +
      ".raft.rpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_jraft_HeartBeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jraft_HeartBeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_HeartBeatRequest_descriptor,
        new java.lang.String[] { "Timestamp", "Payload", });
    internal_static_jraft_HeartBeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jraft_HeartBeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_HeartBeatResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorMessage", "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
