// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consistency.proto

package org.raft.rpc;

/**
 * Protobuf enum {@code WriteType}
 */
public enum WriteType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>WRITE = 0;</code>
   */
  WRITE(0),
  /**
   * <code>DELETE = 1;</code>
   */
  DELETE(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>WRITE = 0;</code>
   */
  public static final int WRITE_VALUE = 0;
  /**
   * <code>DELETE = 1;</code>
   */
  public static final int DELETE_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static WriteType valueOf(int value) {
    return forNumber(value);
  }

  public static WriteType forNumber(int value) {
    switch (value) {
      case 0: return WRITE;
      case 1: return DELETE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<WriteType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      WriteType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<WriteType>() {
          public WriteType findValueByNumber(int number) {
            return WriteType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.raft.rpc.Consistency.getDescriptor().getEnumTypes().get(0);
  }

  private static final WriteType[] VALUES = values();

  public static WriteType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private WriteType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:WriteType)
}

