// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.common.rpc;

/**
 * Protobuf type {@code jraft.ReDistributionKeys}
 */
public  final class ReDistributionKeys extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:jraft.ReDistributionKeys)
    ReDistributionKeysOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReDistributionKeys.newBuilder() to construct.
  private ReDistributionKeys(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReDistributionKeys() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReDistributionKeys();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReDistributionKeys(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              allKeys_ = com.google.protobuf.MapField.newMapField(
                  AllKeysDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ListValue>
            allKeys__ = input.readMessage(
                AllKeysDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            allKeys_.getMutableMap().put(
                allKeys__.getKey(), allKeys__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.common.rpc.Server.internal_static_jraft_ReDistributionKeys_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetAllKeys();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.common.rpc.Server.internal_static_jraft_ReDistributionKeys_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.common.rpc.ReDistributionKeys.class, org.common.rpc.ReDistributionKeys.Builder.class);
  }

  public static final int ALLKEYS_FIELD_NUMBER = 1;
  private static final class AllKeysDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.ListValue> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.ListValue>newDefaultInstance(
                org.common.rpc.Server.internal_static_jraft_ReDistributionKeys_AllKeysEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.google.protobuf.ListValue.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.ListValue> allKeys_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ListValue>
  internalGetAllKeys() {
    if (allKeys_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AllKeysDefaultEntryHolder.defaultEntry);
    }
    return allKeys_;
  }

  public int getAllKeysCount() {
    return internalGetAllKeys().getMap().size();
  }
  /**
   * <code>map&lt;string, .google.protobuf.ListValue&gt; allKeys = 1;</code>
   */

  public boolean containsAllKeys(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetAllKeys().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAllKeysMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.ListValue> getAllKeys() {
    return getAllKeysMap();
  }
  /**
   * <code>map&lt;string, .google.protobuf.ListValue&gt; allKeys = 1;</code>
   */

  public java.util.Map<java.lang.String, com.google.protobuf.ListValue> getAllKeysMap() {
    return internalGetAllKeys().getMap();
  }
  /**
   * <code>map&lt;string, .google.protobuf.ListValue&gt; allKeys = 1;</code>
   */

  public com.google.protobuf.ListValue getAllKeysOrDefault(
      java.lang.String key,
      com.google.protobuf.ListValue defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ListValue> map =
        internalGetAllKeys().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .google.protobuf.ListValue&gt; allKeys = 1;</code>
   */

  public com.google.protobuf.ListValue getAllKeysOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ListValue> map =
        internalGetAllKeys().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetAllKeys(),
        AllKeysDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ListValue> entry
         : internalGetAllKeys().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ListValue>
      allKeys__ = AllKeysDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, allKeys__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.common.rpc.ReDistributionKeys)) {
      return super.equals(obj);
    }
    org.common.rpc.ReDistributionKeys other = (org.common.rpc.ReDistributionKeys) obj;

    if (!internalGetAllKeys().equals(
        other.internalGetAllKeys())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetAllKeys().getMap().isEmpty()) {
      hash = (37 * hash) + ALLKEYS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAllKeys().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.common.rpc.ReDistributionKeys parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.common.rpc.ReDistributionKeys parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.common.rpc.ReDistributionKeys parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.common.rpc.ReDistributionKeys parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.common.rpc.ReDistributionKeys parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.common.rpc.ReDistributionKeys parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.common.rpc.ReDistributionKeys parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.common.rpc.ReDistributionKeys parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.common.rpc.ReDistributionKeys parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.common.rpc.ReDistributionKeys parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.common.rpc.ReDistributionKeys parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.common.rpc.ReDistributionKeys parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.common.rpc.ReDistributionKeys prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code jraft.ReDistributionKeys}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:jraft.ReDistributionKeys)
      org.common.rpc.ReDistributionKeysOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.common.rpc.Server.internal_static_jraft_ReDistributionKeys_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetAllKeys();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableAllKeys();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.common.rpc.Server.internal_static_jraft_ReDistributionKeys_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.common.rpc.ReDistributionKeys.class, org.common.rpc.ReDistributionKeys.Builder.class);
    }

    // Construct using org.common.rpc.ReDistributionKeys.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableAllKeys().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.common.rpc.Server.internal_static_jraft_ReDistributionKeys_descriptor;
    }

    @java.lang.Override
    public org.common.rpc.ReDistributionKeys getDefaultInstanceForType() {
      return org.common.rpc.ReDistributionKeys.getDefaultInstance();
    }

    @java.lang.Override
    public org.common.rpc.ReDistributionKeys build() {
      org.common.rpc.ReDistributionKeys result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.common.rpc.ReDistributionKeys buildPartial() {
      org.common.rpc.ReDistributionKeys result = new org.common.rpc.ReDistributionKeys(this);
      int from_bitField0_ = bitField0_;
      result.allKeys_ = internalGetAllKeys();
      result.allKeys_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.common.rpc.ReDistributionKeys) {
        return mergeFrom((org.common.rpc.ReDistributionKeys)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.common.rpc.ReDistributionKeys other) {
      if (other == org.common.rpc.ReDistributionKeys.getDefaultInstance()) return this;
      internalGetMutableAllKeys().mergeFrom(
          other.internalGetAllKeys());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.common.rpc.ReDistributionKeys parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.common.rpc.ReDistributionKeys) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ListValue> allKeys_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ListValue>
    internalGetAllKeys() {
      if (allKeys_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AllKeysDefaultEntryHolder.defaultEntry);
      }
      return allKeys_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ListValue>
    internalGetMutableAllKeys() {
      onChanged();;
      if (allKeys_ == null) {
        allKeys_ = com.google.protobuf.MapField.newMapField(
            AllKeysDefaultEntryHolder.defaultEntry);
      }
      if (!allKeys_.isMutable()) {
        allKeys_ = allKeys_.copy();
      }
      return allKeys_;
    }

    public int getAllKeysCount() {
      return internalGetAllKeys().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; allKeys = 1;</code>
     */

    public boolean containsAllKeys(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAllKeys().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAllKeysMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ListValue> getAllKeys() {
      return getAllKeysMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; allKeys = 1;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.ListValue> getAllKeysMap() {
      return internalGetAllKeys().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; allKeys = 1;</code>
     */

    public com.google.protobuf.ListValue getAllKeysOrDefault(
        java.lang.String key,
        com.google.protobuf.ListValue defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ListValue> map =
          internalGetAllKeys().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; allKeys = 1;</code>
     */

    public com.google.protobuf.ListValue getAllKeysOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ListValue> map =
          internalGetAllKeys().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAllKeys() {
      internalGetMutableAllKeys().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; allKeys = 1;</code>
     */

    public Builder removeAllKeys(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAllKeys().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ListValue>
    getMutableAllKeys() {
      return internalGetMutableAllKeys().getMutableMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; allKeys = 1;</code>
     */
    public Builder putAllKeys(
        java.lang.String key,
        com.google.protobuf.ListValue value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAllKeys().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .google.protobuf.ListValue&gt; allKeys = 1;</code>
     */

    public Builder putAllAllKeys(
        java.util.Map<java.lang.String, com.google.protobuf.ListValue> values) {
      internalGetMutableAllKeys().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:jraft.ReDistributionKeys)
  }

  // @@protoc_insertion_point(class_scope:jraft.ReDistributionKeys)
  private static final org.common.rpc.ReDistributionKeys DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.common.rpc.ReDistributionKeys();
  }

  public static org.common.rpc.ReDistributionKeys getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReDistributionKeys>
      PARSER = new com.google.protobuf.AbstractParser<ReDistributionKeys>() {
    @java.lang.Override
    public ReDistributionKeys parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReDistributionKeys(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReDistributionKeys> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReDistributionKeys> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.common.rpc.ReDistributionKeys getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

