// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.common.rpc;

public interface ServerMetaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.ServerMetaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 leaderTerm = 1;</code>
   */
  int getLeaderTerm();

  /**
   * <code>string leader = 2;</code>
   */
  java.lang.String getLeader();
  /**
   * <code>string leader = 2;</code>
   */
  com.google.protobuf.ByteString
      getLeaderBytes();

  /**
   * <code>repeated string servers = 3;</code>
   */
  java.util.List<java.lang.String>
      getServersList();
  /**
   * <code>repeated string servers = 3;</code>
   */
  int getServersCount();
  /**
   * <code>repeated string servers = 3;</code>
   */
  java.lang.String getServers(int index);
  /**
   * <code>repeated string servers = 3;</code>
   */
  com.google.protobuf.ByteString
      getServersBytes(int index);
}
