// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.common.rpc;

public interface ServerChangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.ServerChangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *change后的server节点
   * </pre>
   *
   * <code>repeated string servers = 1;</code>
   */
  java.util.List<java.lang.String>
      getServersList();
  /**
   * <pre>
   *change后的server节点
   * </pre>
   *
   * <code>repeated string servers = 1;</code>
   */
  int getServersCount();
  /**
   * <pre>
   *change后的server节点
   * </pre>
   *
   * <code>repeated string servers = 1;</code>
   */
  java.lang.String getServers(int index);
  /**
   * <pre>
   *change后的server节点
   * </pre>
   *
   * <code>repeated string servers = 1;</code>
   */
  com.google.protobuf.ByteString
      getServersBytes(int index);
}
