// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.common.rpc;

/**
 * Protobuf enum {@code jraft.ServerState}
 */
public enum ServerState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LEADER_STOP = 0;</code>
   */
  LEADER_STOP(0),
  /**
   * <code>LEADER_START = 1;</code>
   */
  LEADER_START(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LEADER_STOP = 0;</code>
   */
  public static final int LEADER_STOP_VALUE = 0;
  /**
   * <code>LEADER_START = 1;</code>
   */
  public static final int LEADER_START_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ServerState valueOf(int value) {
    return forNumber(value);
  }

  public static ServerState forNumber(int value) {
    switch (value) {
      case 0: return LEADER_STOP;
      case 1: return LEADER_START;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ServerState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ServerState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ServerState>() {
          public ServerState findValueByNumber(int number) {
            return ServerState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.common.rpc.Server.getDescriptor().getEnumTypes().get(0);
  }

  private static final ServerState[] VALUES = values();

  public static ServerState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ServerState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:jraft.ServerState)
}

