// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.common.rpc;

public interface ServerStateChangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.ServerStateChangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 term = 1;</code>
   */
  int getTerm();

  /**
   * <code>.jraft.ServerState state = 2;</code>
   */
  int getStateValue();
  /**
   * <code>.jraft.ServerState state = 2;</code>
   */
  org.common.rpc.ServerState getState();
}
