// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.common.rpc;

public interface ServerSearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.ServerSearchRequest)
    com.google.protobuf.MessageOrBuilder {
}
