// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.common.rpc;

public final class Server {
  private Server() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_HeartBeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_HeartBeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_HeartBeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_HeartBeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_KeyDistributionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_KeyDistributionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_WorkerReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_WorkerReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_WorkerInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_WorkerInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_ServerChangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_ServerChangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_ServerInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_ServerInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_KeyRuleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_KeyRuleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_KeyRulesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_KeyRulesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_KeyRule_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_KeyRule_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_ServerStateChangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_ServerStateChangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_HotKeyReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_HotKeyReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_ServerConnectedFailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_ServerConnectedFailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_ServerMetaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_ServerMetaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_NoticeLeaderConnectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_NoticeLeaderConnectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_ReDistributionKeys_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_ReDistributionKeys_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_ReDistributionKeys_AllKeysEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_ReDistributionKeys_AllKeysEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\022\005jraft\032\034google/protobuf/s" +
      "truct.proto\032\036google/protobuf/wrappers.pr" +
      "oto\032\021consistency.proto\"T\n\020HeartBeatReque" +
      "st\022/\n\ttimestamp\030\001 \001(\0132\034.google.protobuf." +
      "UInt64Value\022\017\n\007payload\030\002 \001(\014\"H\n\021HeartBea" +
      "tResponse\022\017\n\007success\030\001 \001(\010\022\024\n\014errorMessa" +
      "ge\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\"H\n\026KeyDistributio" +
      "nRequest\022\020\n\010workerId\030\001 \001(\t\022\034\n\004meta\030\002 \001(\013" +
      "2\016.HotKeyRequest\":\n\023WorkerReportRequest\022" +
      "\020\n\010workerId\030\001 \001(\t\022\021\n\tstartTime\030\002 \001(\003\"U\n\021" +
      "WorkerInfoRequest\022.\n\nworkerMeta\030\001 \001(\0132\032." +
      "jraft.WorkerReportRequest\022\020\n\010raftPeer\030\003 " +
      "\001(\t\"&\n\023ServerChangeRequest\022\017\n\007servers\030\001 " +
      "\003(\t\"\'\n\021ServerInfoRequest\022\022\n\nleaderTerm\030\001" +
      " \001(\005\"\036\n\016KeyRuleRequest\022\014\n\004keys\030\001 \003(\t\" \n\020" +
      "KeyRulesResponse\022\014\n\004keys\030\001 \003(\t\"\t\n\007KeyRul" +
      "e\"K\n\030ServerStateChangeRequest\022\014\n\004term\030\001 " +
      "\001(\005\022!\n\005state\030\002 \001(\0162\022.jraft.ServerState\"k" +
      "\n\023HotKeyReportRequest\022\017\n\007appName\030\001 \001(\t\022\013" +
      "\n\003key\030\002 \001(\t\022\r\n\005count\030\003 \001(\003\022\022\n\nintervalMs" +
      "\030\004 \001(\003\022\023\n\013currentTime\030\005 \001(\003\"0\n\032ServerCon" +
      "nectedFailRequest\022\022\n\noldServers\030\001 \003(\t\"I\n" +
      "\022ServerMetaResponse\022\022\n\nleaderTerm\030\001 \001(\005\022" +
      "\016\n\006leader\030\002 \001(\t\022\017\n\007servers\030\003 \003(\t\"\034\n\032Noti" +
      "ceLeaderConnectRequest\"\231\001\n\022ReDistributio" +
      "nKeys\0227\n\007allKeys\030\001 \003(\0132&.jraft.ReDistrib" +
      "utionKeys.AllKeysEntry\032J\n\014AllKeysEntry\022\013" +
      "\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\0132\032.google.prot" +
      "obuf.ListValue:\0028\001*0\n\013ServerState\022\017\n\013LEA" +
      "DER_STOP\020\000\022\020\n\014LEADER_START\020\001B\022\n\016org.comm" +
      "on.rpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          org.common.raft.Consistency.getDescriptor(),
        });
    internal_static_jraft_HeartBeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jraft_HeartBeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_HeartBeatRequest_descriptor,
        new java.lang.String[] { "Timestamp", "Payload", });
    internal_static_jraft_HeartBeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jraft_HeartBeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_HeartBeatResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorMessage", "Data", });
    internal_static_jraft_KeyDistributionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_jraft_KeyDistributionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_KeyDistributionRequest_descriptor,
        new java.lang.String[] { "WorkerId", "Meta", });
    internal_static_jraft_WorkerReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_jraft_WorkerReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_WorkerReportRequest_descriptor,
        new java.lang.String[] { "WorkerId", "StartTime", });
    internal_static_jraft_WorkerInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_jraft_WorkerInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_WorkerInfoRequest_descriptor,
        new java.lang.String[] { "WorkerMeta", "RaftPeer", });
    internal_static_jraft_ServerChangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_jraft_ServerChangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_ServerChangeRequest_descriptor,
        new java.lang.String[] { "Servers", });
    internal_static_jraft_ServerInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_jraft_ServerInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_ServerInfoRequest_descriptor,
        new java.lang.String[] { "LeaderTerm", });
    internal_static_jraft_KeyRuleRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_jraft_KeyRuleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_KeyRuleRequest_descriptor,
        new java.lang.String[] { "Keys", });
    internal_static_jraft_KeyRulesResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_jraft_KeyRulesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_KeyRulesResponse_descriptor,
        new java.lang.String[] { "Keys", });
    internal_static_jraft_KeyRule_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_jraft_KeyRule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_KeyRule_descriptor,
        new java.lang.String[] { });
    internal_static_jraft_ServerStateChangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_jraft_ServerStateChangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_ServerStateChangeRequest_descriptor,
        new java.lang.String[] { "Term", "State", });
    internal_static_jraft_HotKeyReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_jraft_HotKeyReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_HotKeyReportRequest_descriptor,
        new java.lang.String[] { "AppName", "Key", "Count", "IntervalMs", "CurrentTime", });
    internal_static_jraft_ServerConnectedFailRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_jraft_ServerConnectedFailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_ServerConnectedFailRequest_descriptor,
        new java.lang.String[] { "OldServers", });
    internal_static_jraft_ServerMetaResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_jraft_ServerMetaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_ServerMetaResponse_descriptor,
        new java.lang.String[] { "LeaderTerm", "Leader", "Servers", });
    internal_static_jraft_NoticeLeaderConnectRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_jraft_NoticeLeaderConnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_NoticeLeaderConnectRequest_descriptor,
        new java.lang.String[] { });
    internal_static_jraft_ReDistributionKeys_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_jraft_ReDistributionKeys_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_ReDistributionKeys_descriptor,
        new java.lang.String[] { "AllKeys", });
    internal_static_jraft_ReDistributionKeys_AllKeysEntry_descriptor =
      internal_static_jraft_ReDistributionKeys_descriptor.getNestedTypes().get(0);
    internal_static_jraft_ReDistributionKeys_AllKeysEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_ReDistributionKeys_AllKeysEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    org.common.raft.Consistency.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
