// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.common.rpc;

/**
 * Protobuf type {@code jraft.ServerConnectedFailRequest}
 */
public  final class ServerConnectedFailRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:jraft.ServerConnectedFailRequest)
    ServerConnectedFailRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerConnectedFailRequest.newBuilder() to construct.
  private ServerConnectedFailRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerConnectedFailRequest() {
    oldServers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerConnectedFailRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServerConnectedFailRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              oldServers_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            oldServers_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        oldServers_ = oldServers_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.common.rpc.Server.internal_static_jraft_ServerConnectedFailRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.common.rpc.Server.internal_static_jraft_ServerConnectedFailRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.common.rpc.ServerConnectedFailRequest.class, org.common.rpc.ServerConnectedFailRequest.Builder.class);
  }

  public static final int OLDSERVERS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList oldServers_;
  /**
   * <code>repeated string oldServers = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getOldServersList() {
    return oldServers_;
  }
  /**
   * <code>repeated string oldServers = 1;</code>
   */
  public int getOldServersCount() {
    return oldServers_.size();
  }
  /**
   * <code>repeated string oldServers = 1;</code>
   */
  public java.lang.String getOldServers(int index) {
    return oldServers_.get(index);
  }
  /**
   * <code>repeated string oldServers = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOldServersBytes(int index) {
    return oldServers_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < oldServers_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, oldServers_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < oldServers_.size(); i++) {
        dataSize += computeStringSizeNoTag(oldServers_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOldServersList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.common.rpc.ServerConnectedFailRequest)) {
      return super.equals(obj);
    }
    org.common.rpc.ServerConnectedFailRequest other = (org.common.rpc.ServerConnectedFailRequest) obj;

    if (!getOldServersList()
        .equals(other.getOldServersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOldServersCount() > 0) {
      hash = (37 * hash) + OLDSERVERS_FIELD_NUMBER;
      hash = (53 * hash) + getOldServersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.common.rpc.ServerConnectedFailRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.common.rpc.ServerConnectedFailRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.common.rpc.ServerConnectedFailRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.common.rpc.ServerConnectedFailRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.common.rpc.ServerConnectedFailRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.common.rpc.ServerConnectedFailRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.common.rpc.ServerConnectedFailRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.common.rpc.ServerConnectedFailRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.common.rpc.ServerConnectedFailRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.common.rpc.ServerConnectedFailRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.common.rpc.ServerConnectedFailRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.common.rpc.ServerConnectedFailRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.common.rpc.ServerConnectedFailRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code jraft.ServerConnectedFailRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:jraft.ServerConnectedFailRequest)
      org.common.rpc.ServerConnectedFailRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.common.rpc.Server.internal_static_jraft_ServerConnectedFailRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.common.rpc.Server.internal_static_jraft_ServerConnectedFailRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.common.rpc.ServerConnectedFailRequest.class, org.common.rpc.ServerConnectedFailRequest.Builder.class);
    }

    // Construct using org.common.rpc.ServerConnectedFailRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      oldServers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.common.rpc.Server.internal_static_jraft_ServerConnectedFailRequest_descriptor;
    }

    @java.lang.Override
    public org.common.rpc.ServerConnectedFailRequest getDefaultInstanceForType() {
      return org.common.rpc.ServerConnectedFailRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.common.rpc.ServerConnectedFailRequest build() {
      org.common.rpc.ServerConnectedFailRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.common.rpc.ServerConnectedFailRequest buildPartial() {
      org.common.rpc.ServerConnectedFailRequest result = new org.common.rpc.ServerConnectedFailRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        oldServers_ = oldServers_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.oldServers_ = oldServers_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.common.rpc.ServerConnectedFailRequest) {
        return mergeFrom((org.common.rpc.ServerConnectedFailRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.common.rpc.ServerConnectedFailRequest other) {
      if (other == org.common.rpc.ServerConnectedFailRequest.getDefaultInstance()) return this;
      if (!other.oldServers_.isEmpty()) {
        if (oldServers_.isEmpty()) {
          oldServers_ = other.oldServers_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureOldServersIsMutable();
          oldServers_.addAll(other.oldServers_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.common.rpc.ServerConnectedFailRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.common.rpc.ServerConnectedFailRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList oldServers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureOldServersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        oldServers_ = new com.google.protobuf.LazyStringArrayList(oldServers_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string oldServers = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getOldServersList() {
      return oldServers_.getUnmodifiableView();
    }
    /**
     * <code>repeated string oldServers = 1;</code>
     */
    public int getOldServersCount() {
      return oldServers_.size();
    }
    /**
     * <code>repeated string oldServers = 1;</code>
     */
    public java.lang.String getOldServers(int index) {
      return oldServers_.get(index);
    }
    /**
     * <code>repeated string oldServers = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOldServersBytes(int index) {
      return oldServers_.getByteString(index);
    }
    /**
     * <code>repeated string oldServers = 1;</code>
     */
    public Builder setOldServers(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOldServersIsMutable();
      oldServers_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string oldServers = 1;</code>
     */
    public Builder addOldServers(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOldServersIsMutable();
      oldServers_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string oldServers = 1;</code>
     */
    public Builder addAllOldServers(
        java.lang.Iterable<java.lang.String> values) {
      ensureOldServersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, oldServers_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string oldServers = 1;</code>
     */
    public Builder clearOldServers() {
      oldServers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string oldServers = 1;</code>
     */
    public Builder addOldServersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureOldServersIsMutable();
      oldServers_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:jraft.ServerConnectedFailRequest)
  }

  // @@protoc_insertion_point(class_scope:jraft.ServerConnectedFailRequest)
  private static final org.common.rpc.ServerConnectedFailRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.common.rpc.ServerConnectedFailRequest();
  }

  public static org.common.rpc.ServerConnectedFailRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerConnectedFailRequest>
      PARSER = new com.google.protobuf.AbstractParser<ServerConnectedFailRequest>() {
    @java.lang.Override
    public ServerConnectedFailRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServerConnectedFailRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServerConnectedFailRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerConnectedFailRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.common.rpc.ServerConnectedFailRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

