// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.common.rpc;

public interface ServerConnectedFailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.ServerConnectedFailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string oldServers = 1;</code>
   */
  java.util.List<java.lang.String>
      getOldServersList();
  /**
   * <code>repeated string oldServers = 1;</code>
   */
  int getOldServersCount();
  /**
   * <code>repeated string oldServers = 1;</code>
   */
  java.lang.String getOldServers(int index);
  /**
   * <code>repeated string oldServers = 1;</code>
   */
  com.google.protobuf.ByteString
      getOldServersBytes(int index);
}
