// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.common.rpc;

public interface WorkerReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.WorkerReportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string workerId = 1;</code>
   */
  java.lang.String getWorkerId();
  /**
   * <code>string workerId = 1;</code>
   */
  com.google.protobuf.ByteString
      getWorkerIdBytes();

  /**
   * <code>int64 startTime = 2;</code>
   */
  long getStartTime();
}
