// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.common.rpc;

public interface WorkerInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.WorkerInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.jraft.WorkerReportRequest workerMeta = 1;</code>
   */
  boolean hasWorkerMeta();
  /**
   * <code>.jraft.WorkerReportRequest workerMeta = 1;</code>
   */
  org.common.rpc.WorkerReportRequest getWorkerMeta();
  /**
   * <code>.jraft.WorkerReportRequest workerMeta = 1;</code>
   */
  org.common.rpc.WorkerReportRequestOrBuilder getWorkerMetaOrBuilder();

  /**
   * <pre>
   *worker所在的raft节点
   * </pre>
   *
   * <code>string raftPeer = 3;</code>
   */
  java.lang.String getRaftPeer();
  /**
   * <pre>
   *worker所在的raft节点
   * </pre>
   *
   * <code>string raftPeer = 3;</code>
   */
  com.google.protobuf.ByteString
      getRaftPeerBytes();
}
